### ISSUE TITLE
compilation error for OSX Yosmite 

### ISSUE THREAD

**Issue by nick-magnini** [attardi/deepnl#1]
/usr/bin/clang++ -bundle -undefined dynamic_lookup -arch i386 -arch x86_64 -g build/temp.macosx-10.6-x86_64-2.7/deepnl/hpca.o build/temp.macosx-10.6-x86_64-2.7/deepnl/HPCA.o -o build/lib.macosx-10.6-x86_64-2.7/deepnl/hpca.so -fopenmp
ld: library not found for -lgomp
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error: command '/usr/bin/clang++' failed with exit status 1

**Comment by attardi** [comment]
Looks like on you don't have OpenMP installed on your machine.
If you cannot install it, you can remove it from the configuration, by removing from setup.py these lines:
          extra_compile_args=["-fopenmp"]),

**Comment by dungtn** [comment]
/usr/bin/clang++ -bundle -undefined dynamic_lookup -arch x86_64 -arch i386 -Wl,-F. build/temp.macosx-10.10-intel-2.7/deepnl/hpca.o build/temp.macosx-10.10-intel-2.7/deepnl/HPCA.o -o build/lib.macosx-10.10-intel-2.7/deepnl/hpca.so
duplicate symbol _inithpca in:
    build/temp.macosx-10.10-intel-2.7/deepnl/hpca.o
    build/temp.macosx-10.10-intel-2.7/deepnl/HPCA.o
duplicate symbol ___pyx_module_is_main_deepnl__hpca in:
    build/temp.macosx-10.10-intel-2.7/deepnl/hpca.o
    build/temp.macosx-10.10-intel-2.7/deepnl/HPCA.o
ld: 2 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error: command '/usr/bin/clang++' failed with exit status 1

**Comment by attardi** [comment]
Looks like your file system is not configured for case sensitive file names.

**Comment by tralpha** [comment]
Hi @attardi ,
I encountered the same problem as dungtn.

How can i configure my system for case sensitive file names? I made a Google search, and couldn't find a suitable tutorial showing how this can be done.

And moreover, most opinions out there are strongly against making File System case sensitive.

Is there any other way of building the files while still having a case insensitive file system?
