### ISSUE TITLE
TypeError: coercing to Unicode: need string or buffer, file found , while running dl-words.py file

### ISSUE THREAD

**Issue by avinash-k** [attardi/deepnl#12]
I am getting the following error while generating embeddings (vectors.txt). I have given input as vocab.txt a list of words. tried with ascii and utf-8. train file text_corpus contains a list of sentences. This file also experimented with ascii and utf-8. But I am getting the following error.

]$./dl-words.py --verbose --train text_corpus.ascii --vocab vocab.txt --vectors vectors.txt -o embed.dnn
Traceback (most recent call last):
  File "../../deepnl/bin/dl-words.py", line 199, in <module>
    main()
  File "../../deepnl/bin/dl-words.py", line 158, in main
    variant=args.variant)
  File "deepnl/extractors.pyx", line 292, in deepnl.extractors.Embeddings.**init** (deepnl/extractors.cpp:7876)
  File "/usr/lib/python2.7/genericpath.py", line 18, in exists
    os.stat(path)
TypeError: coercing to Unicode: need string or buffer, file found

**Comment by attardi** [comment]
Check if you have the latest release.
Look into file deepnl/word_dictionary.py to see if line 72 reads like this:

            words = list(OrderedDict.fromkeys(wordlist))

**Comment by attardi** [comment]
Quick fix: in file bin/dl-words.py, change line 127 to:
    parser.add_argument('--vectors', required=True,
