### ISSUE TITLE
ValueError: Buffer has wrong number of dimensions (expected 2, got 1)

### ISSUE THREAD

**Issue by kiran-surya** [attardi/deepnl#14]
On the below example, i'm getting Buffer has wrong number of dimensions error. what could be the reason ?
"He called five seconds , man , Im not going to say anything thats going to get me in trouble ,  said Hornets forward Marvin Williams , who was whistled for a five-second inbounds infraction with : 36.6 left in the game ."

**Comment by attardi** [comment]
Are you supplying the input in tsv format?
Otherwise a possible cause is a corrupted vector file.

**Comment by kiran-surya** [comment]
i hosted deepnl as a service. I'm getting this error for some sentences. One such sentence is mentioned above. I'm getting this error during testing.

**Comment by attardi** [comment]
Is it consistent? You always get an error with that sentence?
If so, it might be due to a bad entry in some of the dictionaries created during training.

**Comment by kiran-surya** [comment]
Yes, it is consistent every time i run from service, but if i run as a stand alone query i do not get this error, and i get empty result.

**Comment by kiran-surya** [comment]
Hi,

Any updates on this ?

**Comment by attardi** [comment]
It is an error with the data. I cannot do anything unless I have the data.

**Comment by geovedi** [comment]
i can confirm this problem is related with bad training data as i recently got the same error.

this issue and #6 can be closed.
