### ISSUE TITLE
Compilation Error for OSX El Capitan (Duplicate Symbol, File Insensitive System)

### ISSUE THREAD

**Issue by tralpha** [attardi/deepnl#20]
Hi @attardi ,
I encountered the same problem as dungtn (https://github.com/attardi/deepnl/issues/1)

How can i configure my system for case sensitive file names? I made a Google search, and couldn't find a suitable tutorial showing how this can be done.

And moreover, most opinions out there are strongly against making File System case sensitive.

Is there any other way of building the files while still having a case insensitive file system?

**Comment by attardi** [comment]
File names have been renamed to fix this.
