### ISSUE TITLE
Undefined reference to `hpca::cooccurrence_matrix

### ISSUE THREAD

**Issue by bratao** [attardi/deepnl#22]
Hello, 

Compiling with Mingw I get this error:

build\temp.win32-2.7\Release\deepnl\hpca.o:HPCA.cpp:(.text+0x8d55): undefined reference to `hpca::cooccurrence_matrix(char_, char_, unsigned int, unsigned int)'

In fact, I can´t find any definition of this function.

**Comment by Avmb** [comment]
Isn't it defined [there](https://github.com/attardi/deepnl/blob/master/deepnl/HPCA.cpp#L124)? That one has char \* arguments though.

**Comment by bratao** [comment]
Oh, I understand. Because Windows is not case sensitive, Cython overwrites this file.

**Comment by Avmb** [comment]
I have sent a pull request to fix the issue.
