### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by abdulrehmankhaliq** [attardi/deepnl#27]
While building this library (deepnl) I get a Runtime error "An attempt has been made to start a new process before the current process has finished its boostrapping phase.
This means that you are not using fork to start your child processes and you have forgotten to use the proper idiom in the main module:
if **name**== '**main**:
    freeze_support()'"

**Comment by attardi** [comment]
I have no idea, but the message you are reporting includes a bad code line that does not belong to deepnl, it should read

```
if __name__ == 'main':
```
