### ISSUE TITLE
ImportError: No module named 'cPickle'

### ISSUE THREAD

**Issue by mhbashari** [attardi/deepnl#31]
Running this line of code (python3.4 and ubuntu 14.04):

`from deepnl.tagger import Tagger
`

an error occured

`Traceback (most recent call last):
  File "/home/hassan/PycharmProjects/nlp/__deepnlp.py", line 1, in <module>
    from deepnl.tagger import Tagger
  File "deepnl/extractors.pxd", line 13, in init deepnl.tagger (deepnl/tagger.cpp:7442)
  File "deepnl/extractors.pyx", line 19, in init deepnl.extractors (deepnl/extractors.cpp:25552)
ImportError: No module named 'cPickle'
`

and when try to install with **pip3** got this error:

`Could not find any downloads that satisfy the requirement cpickle
`

**Comment by attardi** [comment]
If you can't install cPickle, replace

```
import cPickle as pickle
```

with

```
import pickle
```

**Comment by Ibrahemamer** [comment]
Wondering if you solved this problem I am getting the same problem even though I changed it to pickle only.

**Comment by hising96** [comment]
try installing future module
pip install future

do get me back on this one if unable to solve

**Comment by meghaSingh1** [comment]
I am getting same problem even after installing future.

**Comment by avinash20111992** [comment]
didn't work for me both  future install and import cPickle as Pickle. can anyone please help.

**Comment by anudeekshith** [comment]
n i am also install futre but still its not working
