### ISSUE TITLE
Unable to install deepnl

### ISSUE THREAD

**Issue by VuceWillis** [attardi/deepnl#35]
I have tried several ways to install deepnl on my windows device. However, using plain conda install doesn't work, since the package cannot be found. Then I tried pip install (pip install git+https://github.com/attardi/deepnl which returns that it cannot find command git) in the anaconda cmd window. Finally I used the same command in the git cmd window which starts off promising, as it starts collecting and cloning. But then it takes forever, uses the full processor power, but it doesn't do anything anymore. And I don't expect an 8mb package to take that long to download and install.

I am not that experienced in git and installing packages if 'conda install' or 'pip install' don't work, but I'd really like to install this deepnl package. Could anyone help me please?

**Comment by VuceWillis** [comment]
$ pip install https://github.com/attardi/deepnl/zipball/master
Collecting https://github.com/attardi/deepnl/zipball/master
  Downloading https://github.com/attardi/deepnl/zipball/master

$ pip install git+https://github.com/attardi/deepnl
Collecting git+https://github.com/attardi/deepnl
  Cloning https://github.com/attardi/deepnl to c:\users\vuk\appdata\local\temp\pip-gbk4ed-build

To make it more clear; I used the commands above (among other commands) and these seem to get closest to installing. However, they both are neverending since they sort of stop "Cloning https://github.com/attardi/deepnl to c:\users\vuk\appdata\local\temp\pip-gbk4ed-build" and can't finish it somehow. I've tried installing another package this way which worked, but the deepnl doensn't want to be installed.

**Comment by attardi** [comment]
There is no need to install the software, you should be able to run the scripts in bin directly.
Otherwise you can do:

```
sudo python setup.py install
```

##

**Comment by VuceWillis** [comment]
ahaa, thank you! Don't know how I missed that.
