### ISSUE TITLE
setup.py problem and __future__ import problem when running dl-words.py

### ISSUE THREAD

**Issue by felicialiu** [attardi/deepnl#37]
I believe I installed everything according to the README, except when I run

> python setup.py build

I get

> 23 warnings generated.
> c++ -bundle -undefined dynamic_lookup -arch x86_64 -arch i386 -Wl,-F. build/temp.macosx-10.9-intel-2.7/deepnl/extractors.o -o build/lib.macosx-10.9-intel-2.7/deepnl/extractors.so
> running build_scripts

I'm not sure if this is normal or something is wrong. In any case, when I try to create word embeddings with dl-words.py I get the following issue:

> Traceback (most recent call last):
>   File "dl-words.py", line 27, in <module>
>     from deepnl.extractors import *
>   File "build/bdist.macosx-10.9-intel/egg/deepnl/extractors.py", line 7, in <module>
>   File "build/bdist.macosx-10.9-intel/egg/deepnl/extractors.py", line 6, in **bootstrap**
>   File "deepnl/extractors.pyx", line 27, in init deepnl.extractors (deepnl/extractors.cpp:25639)
>   File "/Users/felicialiu/mscproject/mscenv/lib/python2.7/site-packages/deepnl-1.3.17-py2.7-macosx-10.9-intel.egg/deepnl/embeddings.py", line 11
> SyntaxError: from `__future__` imports must occur at the beginning of the file

I can only access the embeddings.py that's in my folder, but I can't access the one that is in the virtual environment and edit it. How to fix this problem?

**Comment by attardi** [comment]
Fixed. Thank you.
