### ISSUE TITLE
Train ner model error

### ISSUE THREAD

**Issue by ghaddarAbs** [attardi/deepnl#40]
Note: missing a closing paranthese in line 15 in toIOB.py:
    print('usage:', sys.argv[0], '[-hr] < inFile '

**Comment by usr1993** [comment]
In fact i tried to debug the code with two dataset:
1- Contains only 3 example:
EU NNP B-ORG
rejects VBZ O
German JJ B-MISC

2- Second contains 2 example : 
EU NNP B-ORG
German JJ B-MISC


I noticed that the script run normally with the second sample while throw the above exception with the first example.

**Comment by attardi** [comment]
Fixed, thank you.
