### ISSUE TITLE
Build deepnl

### ISSUE THREAD

**Issue by qizzz** [attardi/deepnl#41]
Is this normal?

Please put "# distutils: language=c++" in your .pyx or .pxd file(s)
Warning: Extension name 'deepnl/words' does not match fully qualified name 'words' of 'deepnl/words.pyx'
deepnl/words.pyx: cannot find cimported module 'trainer'
deepnl/words.pyx: cannot find cimported module 'network'
deepnl/words.pyx: cannot find cimported module 'math'
deepnl/words.pyx: cannot find cimported module 'extractors'
deepnl/words.pxd: cannot find cimported module 'trainer'
deepnl/words.pxd: cannot find cimported module 'network'
Warning: Extension name 'deepnl/hpca' does not match fully qualified name 'hpca' of 'deepnl/hpca.pyx'
deepnl/hpca.pyx: cannot find cimported module 'network'
...

**Comment by attardi** [comment]
Not normal, it is already there.
Did you install Cython?

**Comment by qizzz** [comment]
Thanks a lot for the reply, Giuseppe! Yes, I've installed Cython... After I built with this problem, I couldn't run scripts under bin/, since every time I ran them, it would give me error like "no deepnl module" in the lines of importing deepnl, deepnl.network etc.

**Comment by MelodiousThonk** [comment]
I have the same problem

**Comment by liyumeng** [comment]
I have the same problem, then I create an empty file named `__init__.py` in `deepnl/deepnl/`. It's solved!

**Comment by attardi** [comment]
Good suggestion.
Fixed.
